sonata_admin:
  title: 'Sonata Admin'
  dashboard:
    blocks:
      - { type: sonata.admin.block.admin_list, position: left }
    groups:
      sonata.admin.group.administration:
        label: sonata_administration
        label_catalogue: SonataAdminBundle
        icon: '<i class="fa fa-cogs"></i>'
        items:
          - App\Admin\BookAdmin
          - App\Admin\AuthorAdmin
sonata_block:
  blocks:
    sonata.admin.block.admin_list:
      contexts: [ admin ]